# Generated by Django 5.1.3 on 2024-11-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_file_upload_alter_post_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head_image',
        ),
    ]
