# Generated by Django 5.1.3 on 2024-11-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_content_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='hook_text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
